"""README.md assembly. GitHub allows only sanitized HTML: images, links, <p align>, <picture>."""
from __future__ import annotations

from dataclasses import dataclass

from generator.pixel import esc

GENERATED_NOTE = "<!-- Generated by generator/build.py. Edit profile.yml instead. -->"


@dataclass(frozen=True)
class Card:
    src: str
    alt: str
    width: str
    href: str | None = None


def _card_html(card: Card) -> str:
    img = f'<img src="{esc(card.src)}" alt="{esc(card.alt)}" width="{card.width}">'
    return f'<a href="{esc(card.href)}">{img}</a>' if card.href else img


def row(cards: list[Card]) -> str:
    return '<p align="center">\n' + "\n".join(_card_html(c) for c in cards) + "\n</p>"


def pacman(user: str) -> str:
    base = f"https://raw.githubusercontent.com/{user}/{user}/output/pacman-contribution-graph"
    return (
        '<p align="center">\n<picture>\n'
        f'  <source media="(prefers-color-scheme: dark)" srcset="{base}-dark.svg">\n'
        f'  <source media="(prefers-color-scheme: light)" srcset="{base}.svg">\n'
        f'  <img alt="Pac-Man eating the contribution graph" src="{base}.svg" width="100%">\n'
        "</picture>\n</p>"
    )


def render_readme(blocks: list[str]) -> str:
    return GENERATED_NOTE + "\n\n" + "\n\n".join(blocks) + "\n"


def render_preview(readme: str) -> str:
    body = readme.replace(GENERATED_NOTE, "")

    def column(theme: str, bg: str, fg: str) -> str:
        return (f'<section style="background:{bg};color:{fg};padding:24px;width:830px;'
                f'font-family:sans-serif"><h3>{theme}</h3>{body}</section>')

    return ("<!doctype html><meta charset=utf-8><title>Profile preview</title>"
            "<body style=\"margin:0;padding:24px;display:flex;gap:24px;flex-wrap:wrap;background:#6e7681\">"
            + column("GitHub dark", "#0d1117", "#e6edf3")
            + column("GitHub light", "#ffffff", "#1f2328")
            + "</body>")
